// export const appImports = {
// import { Routes, Route, BrowserRouter } from "react-router-dom";
// import LandingPage from "./pages/LandingPage";
// import PrivacyPolicy from "./pages/PrivacyPolicy";
// import TermsOfServices from "./pages/TermsOfServices";
// import Auth from "./components/Auth";
// import Signup from "./pages/Signup";
// import Login from "./pages/Login";
// import VerifyOtp from "./pages/VerifyOtp";
// import ForgotPassword from "./pages/ForgotPassword";
// import ResetPassword from "./pages/ResetPassword";
// import AppLayout from "./ui/AppLayout";
// import Dashboard from "./pages/Dashboard";
// import MyProjects from "./pages/MyProjects";
// import Members from "./pages/Members";
// import Projects from "./pages/Projects";
// import Analytics from "./pages/Analytics";
// import Trash from "./pages/Trash";
// import Profile from "./pages/Profile";
// import Messages from "./pages/Messages";
// import Notifications from "./pages/Notifications";
// import Project from "./pages/Project";
// import AllTasks from "./pages/AllTasks";
// import Task from "./pages/Task";
// import Info from "./ui/Info";
// import Assets from "./ui/Assets";
// import TaskMembers from "./ui/TaskMembers";
// import Comments from "./ui/Comments";
// import AnalyticsList from "./pages/AnalyticsList";
// import { UserContextProvider } from "./context/UserContext";
// };
